apiVersion: v1
kind: Service
metadata:
  name: ttm-service
  labels:
    app: ttm
spec:
  ports:
  - port: 8081
  selector:
    app: ttm-server
---
apiVersion: v1
kind: Route
metadata:
  name: ttm-route
  labels:
    app: ttm
spec:
  host: ttm-test.rahtiapp.fi
  to:
    kind: Service
    name: ttm-service
    # weight: 100
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ttm-server
  labels:
    app: ttm
spec:
  selector:
    matchLabels:
      app: ttm-server
  replicas: 2
  template:
    metadata:
      labels:
        app: ttm-server
    spec:
      containers:
      - name: nginx
        image: ghcr.io/eemilhaa/travel-time-matrix-visualisation-backend:deploy-rahti
        ports:
        - containerPort: 8081  # unprivileged
        requests:
          memory: "200M"
          cpu: "200m"
        limits:
          memory: "1G"
          cpu: "1"
